Add missing args to CIIClient.onDisconnected() call
Fixes exception (got on python 3.5):
...
  File "/opt/hbbtv-msas/dvbcss/protocol/client/cii.py", line 390, in _onConnectionClose
    self.onDisconnected()
TypeError: onDisconnected() missing 1 required positional argument: 'code'